### ISSUE TITLE
Cloud Refactor

### ISSUE THREAD

**Issue by nikogu** [antvis/data-set#10]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud.html

**Comment by leungwensen** [comment]
Done

@antvis/g2@3.0.2 &&  @antv/data-set@0.8.0

[word-cloud](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud.html) [word-cloud with image mask](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud-mask.html)
