### ISSUE TITLE
DataSet与Mobx共同使用时的问题

### ISSUE THREAD

**Issue by xiaoji121** [antvis/data-set#16]
* **Link**:

代码：

```javascript
const ds = new DataSet();
const dv = ds.createView().source(dataSource);
```

* **Platform**:

* **Mini Showcase(like screenshots)**:

当dataSource是一个mobx的ObservableArray时，会抛错

![image](https://user-images.githubusercontent.com/1305754/34343912-5587a6ee-ea19-11e7-8008-d31e89c9ed7a.png)

**Comment by leungwensen** [comment]
DataSet 暂不支持非原生标准的数据结构。你可以把它先转换成原生的对象数组。
