### ISSUE TITLE
在ie9里不能够显示图表报引发了异常但未捕获的错误

### ISSUE THREAD

**Issue by yangmeiz** [antvis/data-set#21]
在ie9为什么他又报 “引发了异常但未捕获data-set.min.js (1,30929)”
this.dataSet);else if(Array.isArray(n))this.origin=n;else{if(!f(n)||!n.type) 这是data-set.min.js中的那行代码

**Comment by yangmeiz** [comment]
怎么关闭线程呢？？

**Comment by leungwensen** [comment]
@yangmeiz 已经发好了，`@antv/data-set@0.8.4`
