### ISSUE TITLE
the JS bundle built from this tool is so large

### ISSUE THREAD

**Issue by orangeyyy** [antvis/data-set#23]
I only use the tranform of this tool, but I found the js bundle built from this tool is so large:
without uglify:
![image](https://user-images.githubusercontent.com/19667299/35613122-0fe8cc18-06a6-11e8-9bfa-fef1cb40366a.png)
with uglify:
![image](https://user-images.githubusercontent.com/19667299/35613134-1e7bafb6-06a6-11e8-8ab7-e81ff34d5a69.png)

could you do some code splitting for this tool?

**Comment by leungwensen** [comment]
You can use connectors or transforms independently by `require` the source file directly. For example, if you only need to handle hexjson files, you can use `data-set` like this:

```js
import '@antv/data-set/src/connector/hexjson';
import DataSet from '@antv/data-set/src/data-set';

const dv = new DataSet.View().source(data, {
  type: 'hex',
  width: 100,
  height: 100
});
```

**Comment by leungwensen** [comment]
In fact, **ALL connectors and transforms are Pluggable**. https://github.com/antvis/data-set/blob/master/index.js

**Comment by orangeyyy** [comment]
got it.  THX

**Comment by ChiaJune** [comment]
您好，我使用`import DataSet from '@antv/data-set/src/data-set';`这种方式按需加载，会报错，提示`transform is not a function`，现在只能全量引入么？

**Comment by leungwensen** [comment]
@ChiaJune 引用这个文件： https://github.com/antvis/data-set/blob/master/src/index.js 如果需要按需引用，也参考这个文件的写法，只是相对路径写成绝对路径（require('./api/statistics'); -> require('@antv/data-set/src/api/statistics');）

**Comment by winjeysong** [comment]
请问什么时候支持按需引入呢。。引用data-set包的部分功能，还得一个一个从src目录下引入，这样每次build之前还得额外用babel处理一下才能uglify😢😢

**Comment by Keillion** [comment]
> 
> 
> @ChiaJune 引用这个文件： https://github.com/antvis/data-set/blob/master/src/index.js 如果需要按需引用，也参考这个文件的写法，只是相对路径写成绝对路径（require('./api/statistics'); -> require('@antv/data-set/src/api/statistics');）

现在可以参考 https://github.com/antvis/data-set/blob/master/src/index.ts

**Comment by sameenzm** [comment]
> 您好，我使用`import DataSet from '@antv/data-set/src/data-set';`这种方式按需加载，会报错，提示`transform is not a function`，现在只能全量引入么？

请问您最后怎么解决的？

**Comment by Keillion** [comment]
@sameenzm 
Example from my project:
```ts
// load used codes only
// https://github.com/antvis/data-set/blob/master/src/index.ts
import '@antv/data-set/lib/connector/default';
import '@antv/data-set/lib/transform/fold';
import { DataSet } from "@antv/data-set/lib/data-set";
```
