### ISSUE TITLE
韦恩图需求

### ISSUE THREAD

**Issue by lantang955** [antvis/data-set#24]
需求背景：业务上重合度分析时，需要通过venn图来表达
需求内容：
       g2上增加venn图模块，具体具体需求点如下：
1.需求支持2组，3组，4组，5组.....n组的数据展示
![image](https://user-images.githubusercontent.com/36022365/35659622-34c902ae-0742-11e8-816c-908a50f196fb.png)

2.每一组的数据颜色可调（相交部分不需要调整，按自然颜色重叠来）
3.每一块数据的面积大小可表达给出的数值大小（比例不用太精确，可表达数值间的比较意图即可），但可能出现极大值和极小值，导致极小值看不见的情况，需要有上下限
4.图形区域上展示数字，如展示不下的，通过连线方式指引，展示到空白区域
5.在空白处，可选择是否展示每组数据的总和数字
需求样例（以3组数据为例）：
![image](https://user-images.githubusercontent.com/36022365/35659871-ad91c846-0743-11e8-8732-fd088a94b53d.png)
![image](https://user-images.githubusercontent.com/36022365/35659877-b4e1178c-0743-11e8-97e4-4aa247108add.png)

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/venn.html#
