### ISSUE TITLE
data-set能否进行功能拆分？

### ISSUE THREAD

**Issue by orangeyyy** [antvis/data-set#28]
* **Link**:
* **Platform**:
* **Mini Showcase(like screenshots)**:

我只想用一些简单的transform功能，但是要引入整个data-set包太不合理，而且data-set包不是一般的大，能够将各个功能点进行拆分，让使用者可以按需加载？

**Comment by leungwensen** [comment]
你不是提过这个问题了吗？

https://github.com/antvis/data-set/issues/23

**Comment by leungwensen** [comment]
所有的 connector 和 transform 都是注册式地声明的，完全可以按需加载

**Comment by orangeyyy** [comment]
我是想说这种方式对于用户非常不友好，好多依赖不看代码，根本就不知道你们是怎么依赖的

**Comment by orangeyyy** [comment]
比如 DataView里面有个range方法

**Comment by leungwensen** [comment]
我们会整理一次 G2 和 DataSet 的模块，开发按需加载功能排期到五月份之后了，到时候给个官方的按需加载的方案吧。
