### ISSUE TITLE
lib目录下存在ES6语法

### ISSUE THREAD

**Issue by orangeyyy** [antvis/data-set#36]
按照项目package.json中的配置，lib目录下应该是存放babel编译之后的代码，但是发现其中依然存在ES6语法：
view.js
```
class View extends EventEmitter {
...
}
```
data-set.js 
```
class DataSet extends EventEmitter {
...
}
```
一般我们在进行项目webpack打包的时候习惯将node_modules下的文件exclude，因此希望能够提供的lib目录下不要出现ES6语法。

**Comment by leungwensen** [comment]
的确，我修复一下发个版本

**Comment by leungwensen** [comment]
@orangeyyy 请升级到 `@antv/data-set@0.8.9`
