### ISSUE TITLE
Yarn应该如何安装@antv/data-set依赖？

### ISSUE THREAD

**Issue by Bruce-zxy** [antvis/data-set#37]
Yarn Version: 1.0.0

我在create-react-app脚手架下想使用data-set，但是使用yarn add @antv/data-set命令安装时报错：
![image](https://user-images.githubusercontent.com/22904758/40051052-f01ecc3a-586b-11e8-8bd1-1e17ba247f52.png)

如果去掉@antv的话就会去安装重名包data-set@4.0.0
我查询了yarn中文官网提供的add参数：
![image](https://user-images.githubusercontent.com/22904758/40051344-f69edef0-586c-11e8-841d-097b263c78d2.png)

发现可能安装的好像只有yarn add \<git remote url\>方式
但是我通过这种方式总是会卡死在Resolving Packages
![image](https://user-images.githubusercontent.com/22904758/40051396-2f97ad7c-586d-11e8-8e21-caa4344895df.png)

我想请问一下是不是用yarn安装的话只能通过git remote url的方式呢？

**Comment by leungwensen** [comment]
是 windows 环境对吧？我做个实验

**Comment by Bruce-zxy** [comment]
@leungwensen 是的  Windows  7

**Comment by leungwensen** [comment]
你检查一下 `@` 是不是输入成全角字符了。我在 win10 下 powershell 和 git bash 试了环境都没问题

**Comment by Bruce-zxy** [comment]
@leungwensen 我用美式英文键盘安装的情况是
1、GitBash安装没问题（之前没试过）
2、CMD安装没问题（之前也没试过）
3、PowerShell还是会有问题

![image](https://user-images.githubusercontent.com/22904758/40093589-88094514-58f5-11e8-9c04-afcc973b9421.png)


不过这至少说明了跟data-set包没有任何关系，谢谢了
我去看看PowerShell的文档

**Comment by leungwensen** [comment]
嗯嗯，多谢反馈。
