### ISSUE TITLE
内部依赖 lodash，导致覆盖全局_变量

### ISSUE THREAD

**Issue by maplor** [antvis/data-set#42]
版本 0.9.4
从最终打包版本看，内部约有12处依赖了 lodash，导致引入 data-set 后会覆盖 window._ 变量

**Comment by leungwensen** [comment]
1. 按需打包把 dagre 依赖去掉
2. 把 dataset 脚本放到 underscore 脚本前面
3. 用 CMD 的方式引用 lodash 或者 underscore，不要从全局拿

**Comment by linkHe12** [comment]
因为 package.json 中配置了 browser 指向的是 build 后的 umd 包 ，lodash 被以 amd parser 解析到了这个包里导致覆盖 window._ 变量。
如果你在用 webpack，我目前的做法是配了一个 alias 强制指向了 `@antv/data-set/src/index.js`，同时配置 lodash 的 parser，禁用掉 amd。这样防止 lodash 覆盖 `window._` 变量
[#3017](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512)
