### ISSUE TITLE
精度处理异常

### ISSUE THREAD

**Issue by Arweil** [antvis/data-set#46]
transform percent
![image](https://user-images.githubusercontent.com/13160193/47844008-3fff6780-ddfc-11e8-9010-6248dd5c6874.png)

**Comment by leungwensen** [comment]
这是 js 的问题，你可以再执行一个 map transform，用 toFixed 处理一下数字精度

**Comment by Arweil** [comment]
所以在使用类似饼状图并且使用transform percent的时候，必须使用transform map方法进行tofixed精度处理。
是否可以在transform percent的API中加入精度处理。

**Comment by yangwe1** [comment]
> 这是 js 的问题，你可以再执行一个 map transform，用 toFixed 处理一下数字精度

感谢，那#94 也可以这样曲线救国
