### ISSUE TITLE
如何在typescript中使用@antv/data-set，缺少声明文件

### ISSUE THREAD

**Issue by lxsunbin** [antvis/data-set#57]
* **Link**:
* **Platform**:
* **Mini Showcase(like screenshots)**:

**Comment by leungwensen** [comment]
#43

**Comment by shen1986** [comment]
不用ts语法，直接就可以使用了。
`const DataSet = require('@antv/data-set');`

**Comment by shen1986** [comment]
![image](https://user-images.githubusercontent.com/35757672/55532030-f2ef2c80-56de-11e9-9d9f-73c84cde4eaa.png)

**Comment by lxsunbin** [comment]
> 不用ts语法，直接就可以使用了。
> `const DataSet = require('@antv/data-set');`

可以了，谢谢
