### ISSUE TITLE
找不到API文档

### ISSUE THREAD

**Issue by Enginebeck** [antvis/data-set#60]
* **Link**: [dataset home page](https://github.com/antvis/data-set)
* **Mini Showcase(like screenshots)**:

![image](https://user-images.githubusercontent.com/9574537/62600602-dcbddb00-b921-11e9-800e-1a9bbaf7b37a.png)
图片所示链接点击后跳转到antv首页，最终导致找不到API文档究竟在哪里

**Comment by wupeiwen** [comment]
https://www.yuque.com/antv/g2-docs/tutorial-dataset

**Comment by coolguy001tv** [comment]
+1 为什么一直没有处理。。。

**Comment by simaQ** [comment]
文档在这里： https://g2.antv.vision/zh/docs/api/data-set
