### ISSUE TITLE
支付宝小程序词云需求

### ISSUE THREAD

**Issue by FernAbby** [antvis/data-set#64]
支付宝小程序要写一个词云，头秃

**Comment by leungwensen** [comment]
到这里提个 issue： https://github.com/ant-mini-program/mini-chart

**Comment by alobe** [comment]
<img width="274" alt="截屏2021-02-01 下午5 04 52" src="https://user-images.githubusercontent.com/16461608/106436947-ad087880-64af-11eb-882e-91bff54d9986.png">
tag-cloud.ts有计划支持小程序上的canvas上下文么？
看着是直接引用了d3-cloud的词云算法
